export const SHOW_COMMENT_LIST = 'SHOW_COMMENT_LIST';
export const HIDE_COMMENT_LIST = 'HIDE_COMMENT_LIST';
export const SHOW_SHARE_MODAL = 'SHOW_SHARE_MODAL';
export const HIDE_SHARE_MODAL = 'HIDE_SHARE_MODAL';
