export const LIKE_USER_PROFILE = 'LIKE_USER_PROFILE';
export const UNLIKE_USER_PROFILE = 'UNLIKE_USER_PROFILE';
export const FOLLOW_USER_PROFILE = 'FOLLOW_USER_PROFILE';
export const UNFOLLOW_USER_PROFILE = 'UNFOLLOW_USER_PROFILE';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILED = 'FETCH_USER_PROFILE_FAILED';
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT';
